import {defineArrayMember, defineField, defineType} from 'sanity'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',
  description: 'Business info, homepage, about page, and shared site copy.',
  fields: [
    defineField({
      name: 'name',
      title: 'Business name',
      type: 'string',
      description: 'Business name. Used in the browser tab, footer copyright, and page titles.',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'tagline',
      title: 'Tagline',
      type: 'string',
      description: 'Short tagline under the logo on the homepage and in the footer.',
    }),
    defineField({
      name: 'description',
      title: 'Site description',
      type: 'text',
      rows: 3,
      description: 'One-sentence summary of the bakery. Shown on the homepage hero and in search/social previews.',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'contact',
      title: 'Contact',
      type: 'object',
      description: 'Contact details shown on the Contact page, footer, and order form.',
      fields: [
        defineField({
          name: 'email',
          title: 'Email',
          type: 'string',
          description: 'Contact email. Shown on the Contact page and footer.',
          validation: (rule) => rule.required(),
        }),
        defineField({
          name: 'phone',
          title: 'Phone',
          type: 'string',
          description: 'Phone number. Shown on the Contact page and footer.',
          validation: (rule) => rule.required(),
        }),
        defineField({
          name: 'hours',
          title: 'Hours',
          type: 'string',
          description: 'Business hours. Shown on the Contact page and footer.',
          validation: (rule) => rule.required(),
        }),
        defineField({
          name: 'location',
          title: 'Location',
          type: 'string',
          description: 'City/area label, e.g. "Carmel, Indiana". Shown on the Contact page.',
          validation: (rule) => rule.required(),
        }),
        defineField({
          name: 'address',
          title: 'Kitchen address',
          type: 'object',
          description: 'Home kitchen address. Shown in the footer and on the order form disclaimer.',
          fields: [
            defineField({
              name: 'street',
              title: 'Street',
              type: 'string',
              description: 'Street address. Shown in the footer and order form.',
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: 'city',
              title: 'City',
              type: 'string',
              description: 'City. Shown in the footer and order form.',
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: 'state',
              title: 'State',
              type: 'string',
              description: 'State abbreviation, e.g. "IN". Shown in the footer and order form.',
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: 'zip',
              title: 'ZIP',
              type: 'string',
              description: 'ZIP code. Shown in the footer and order form.',
              validation: (rule) => rule.required(),
            }),
          ],
        }),
      ],
    }),
    defineField({
      name: 'social',
      title: 'Social',
      type: 'object',
      description: 'Social media links shown in the footer.',
      fields: [
        defineField({
          name: 'links',
          title: 'Social links',
          type: 'array',
          description: 'Add one entry per platform. Each link appears in the footer "Follow along" section.',
          of: [
            defineArrayMember({
              type: 'object',
              fields: [
                defineField({
                  name: 'icon',
                  title: 'Icon',
                  type: 'string',
                  description: 'Which icon to display in the footer.',
                  options: {
                    list: [
                      {title: 'Instagram', value: 'instagram'},
                      {title: 'TikTok', value: 'tiktok'},
                      {title: 'Facebook', value: 'facebook'},
                    ],
                  },
                  validation: (rule) => rule.required(),
                }),
                defineField({
                  name: 'name',
                  title: 'Platform name',
                  type: 'string',
                  description: 'Platform name for accessibility, e.g. "Instagram".',
                  validation: (rule) => rule.required(),
                }),
                defineField({
                  name: 'url',
                  title: 'URL',
                  type: 'url',
                  description: 'Full profile URL. Used as the link in the footer.',
                  validation: (rule) => rule.required(),
                }),
                defineField({
                  name: 'label',
                  title: 'Display label',
                  type: 'string',
                  description: 'Visible link text in the footer, e.g. "@love.kycakes".',
                  validation: (rule) => rule.required(),
                }),
              ],
              preview: {
                select: {title: 'name', subtitle: 'label'},
              },
            }),
          ],
        }),
      ],
    }),
    defineField({
      name: 'home',
      title: 'Homepage',
      type: 'object',
      description: 'Content for the homepage hero and cake spotlight section.',
      fields: [
        defineField({
          name: 'heroImage',
          title: 'Hero image',
          type: 'image',
          options: {hotspot: true},
          description: 'Large cake photo in the homepage hero (right side). Falls back to the default image if empty.',
        }),
        defineField({
          name: 'spotlight',
          title: 'Cake spotlight',
          type: 'object',
          description: '"The Cake" section on the homepage, below the hero.',
          fields: [
            defineField({
              name: 'title',
              title: 'Title',
              type: 'string',
              description: 'Main heading in the homepage spotlight section.',
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: 'subhead',
              title: 'Subhead',
              type: 'string',
              description: 'Bold line under the spotlight title on the homepage.',
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: 'text',
              title: 'Body text',
              type: 'text',
              rows: 4,
              description: 'Main paragraph in the homepage spotlight section.',
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: 'ingredientNote',
              title: 'Ingredient note',
              type: 'text',
              rows: 2,
              description: 'Smaller note about ingredients, shown below the spotlight body text.',
            }),
            defineField({
              name: 'ctaLabel',
              title: 'CTA button label',
              type: 'string',
              description: 'Text on the "Order" button in the spotlight section, e.g. "Order Yours".',
            }),
            defineField({
              name: 'secondaryLine',
              title: 'Secondary line',
              type: 'string',
              description: 'Small line under the spotlight button, e.g. "Made to order | Home-baked in Carmel".',
            }),
            defineField({
              name: 'image',
              title: 'Spotlight photo',
              type: 'image',
              options: {hotspot: true},
              description: 'Tall cake photo on the left side of the homepage spotlight section.',
            }),
          ],
        }),
      ],
    }),
    defineField({
      name: 'order',
      title: 'Order page',
      type: 'object',
      description: 'Shared copy for the Order page. Individual cakes are managed under Products.',
      fields: [
        defineField({
          name: 'intro',
          title: 'Order intro',
          type: 'text',
          rows: 2,
          description: 'Paragraph under the "Good Taste Awaits..." heading on the Order page.',
          validation: (rule) => rule.required(),
        }),
        defineField({
          name: 'deliveryNote',
          title: 'Delivery note',
          type: 'string',
          description: 'Small note under the cake price on the Order page, e.g. "Kylee will confirm your order…".',
          validation: (rule) => rule.required(),
        }),
        defineField({
          name: 'disclaimer',
          title: 'Disclaimer',
          type: 'text',
          rows: 2,
          description: 'Legal disclaimer above the checkbox on the Order page.',
          validation: (rule) => rule.required(),
        }),
        defineField({
          name: 'message',
          title: 'Order closing message',
          type: 'array',
          description: 'Personal note(s) shown in the box below the order form. Add one array item per paragraph.',
          of: [defineArrayMember({type: 'text', rows: 3})],
        }),
      ],
    }),
    defineField({
      name: 'about',
      title: 'About',
      type: 'object',
      description: 'Content for the About page.',
      fields: [
        defineField({
          name: 'title',
          title: 'Page title',
          type: 'string',
          description: 'Main heading at the top of the About page, e.g. "Hi, I\'m Kylee."',
          validation: (rule) => rule.required(),
        }),
        defineField({
          name: 'subhead',
          title: 'Subhead',
          type: 'string',
          description: 'Bold line under the About page title.',
          validation: (rule) => rule.required(),
        }),
        defineField({
          name: 'pullQuote',
          title: 'Pull quote paragraph',
          type: 'string',
          description: 'Must match one bio paragraph exactly — that paragraph gets special styling on the About page.',
        }),
        defineField({
          name: 'paragraphs',
          title: 'Bio paragraphs',
          type: 'array',
          description: 'Kylee\'s story, one paragraph per item. HTML like <em> tags is allowed for emphasis.',
          of: [defineArrayMember({type: 'text', rows: 3})],
          validation: (rule) => rule.required().min(1),
        }),
        defineField({
          name: 'ownerImage',
          title: 'Owner photo',
          type: 'image',
          options: {hotspot: true},
          description: 'Main photo on the About page (right column). Shows a placeholder if empty.',
        }),
        defineField({
          name: 'galleryPhotos',
          title: 'Gallery photos',
          type: 'array',
          description: 'Two smaller tilted photos below the main About photo. Shows placeholders if empty.',
          of: [
            defineArrayMember({
              type: 'object',
              fields: [
                defineField({
                  name: 'image',
                  title: 'Photo',
                  type: 'image',
                  options: {hotspot: true},
                  description: 'Gallery image. Leave empty to show a "Photo coming soon" placeholder.',
                }),
                defineField({
                  name: 'side',
                  title: 'Tilt side',
                  type: 'string',
                  description: 'Which direction the photo tilts on the About page.',
                  options: {
                    list: [
                      {title: 'Right', value: 'right'},
                      {title: 'Left', value: 'left'},
                    ],
                  },
                  initialValue: 'right',
                }),
              ],
              preview: {
                select: {title: 'side', media: 'image'},
              },
            }),
          ],
        }),
      ],
    }),
    defineField({
      name: 'reviews',
      title: 'Reviews',
      type: 'array',
      description: 'Customer reviews shown on the Reviews page and the first two on the homepage.',
      of: [
        defineArrayMember({
          type: 'object',
          fields: [
            defineField({
              name: 'quote',
              title: 'Quote',
              type: 'text',
              rows: 3,
              description: 'The review text.',
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: 'author',
              title: 'Author',
              type: 'string',
              description: 'Who wrote the review, e.g. "Love, Ky Cakes customer".',
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: 'isPlaceholder',
              title: 'Placeholder review',
              type: 'boolean',
              initialValue: false,
              description: 'Check to show faded "coming soon" styling instead of a real review.',
            }),
          ],
          preview: {
            select: {title: 'author', subtitle: 'quote'},
          },
        }),
      ],
    }),
    defineField({
      name: 'seo',
      title: 'SEO descriptions',
      type: 'object',
      description: 'Short descriptions for search engines and social sharing. One per page.',
      fields: [
        defineField({
          name: 'about',
          title: 'About page',
          type: 'text',
          rows: 2,
          description: 'Meta description for the About page (browser tab and Google).',
        }),
        defineField({
          name: 'contact',
          title: 'Contact page',
          type: 'text',
          rows: 2,
          description: 'Meta description for the Contact page.',
        }),
        defineField({
          name: 'order',
          title: 'Order page',
          type: 'text',
          rows: 2,
          description: 'Meta description for the Order page.',
        }),
        defineField({
          name: 'reviews',
          title: 'Reviews page',
          type: 'text',
          rows: 2,
          description: 'Meta description for the Reviews page.',
        }),
      ],
    }),
    defineField({
      name: 'formspreeOrderEndpoint',
      title: 'Formspree order endpoint',
      type: 'string',
      description: 'Formspree URL (e.g. https://formspree.io/f/xxxxx). Powers the Order page submit button.',
    }),
  ],
  preview: {
    prepare() {
      return {title: 'Site Settings'}
    },
  },
})
